//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruimentAgencyAppIS4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompanii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kompanii()
        {
            this.Polzovateli = new HashSet<Polzovateli>();
            this.Vacansies = new HashSet<Vacansies>();
        }
    
        public int id { get; set; }
        public int idNaimenovanieKompanii { get; set; }
        public long INN { get; set; }
        public long OGRN { get; set; }
        public Nullable<System.DateTime> DataRegistratia { get; set; }
        public string UridicheskiyAdres { get; set; }
        public string Rukovoditel { get; set; }
        public string OpisanieKompanii { get; set; }
    
        public virtual KompaniNaimenovanie KompaniNaimenovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovateli> Polzovateli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacansies> Vacansies { get; set; }
    }
}
