//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruimentAgencyAppIS4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecruimentAgencyEntities1 : DbContext
    {
        public RecruimentAgencyEntities1()
            : base("name=RecruimentAgencyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant> Applicant { get; set; }
        public virtual DbSet<Doljnost> Doljnost { get; set; }
        public virtual DbSet<Goroda> Goroda { get; set; }
        public virtual DbSet<Grajdanstvo> Grajdanstvo { get; set; }
        public virtual DbSet<Kompanii> Kompanii { get; set; }
        public virtual DbSet<KompaniNaimenovanie> KompaniNaimenovanie { get; set; }
        public virtual DbSet<MestoRabotu> MestoRabotu { get; set; }
        public virtual DbSet<NaimenovanieVacanciy> NaimenovanieVacanciy { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<RegionNaimenovanie> RegionNaimenovanie { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Specializacii> Specializacii { get; set; }
        public virtual DbSet<Specialnost> Specialnost { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vacansies> Vacansies { get; set; }
    }
}
