//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruimentAgencyAppIS4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int idRole { get; set; }
        public Nullable<int> idApplicant { get; set; }
        public Nullable<int> idKompanii { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Kompanii Kompanii { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
